### ISSUE TITLE
[org.geysermc.geyser.event.GeyserEventBus] An exception occurred while executing event  for subscriber org.geysermc.geyser.event.GeyserEventSubscriber

### ISSUE THREAD

**Issue by hydevbiz** [onebeastchris/packs-extension#26]
[23:53:59 ERROR]: [org.geysermc.geyser.event.GeyserEventBus] An exception occurred while executing event  for subscriber org.geysermc.geyser.event.GeyserEventSubscriber
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.mappings" is null
        at Geyser-Spigot.jar/org.geysermc.geyser.registry.AbstractMappedRegistry.get(AbstractMappedRegistry.java:57) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.GeyserImpl.provider(GeyserImpl.java:792) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.api.command.Command.builder(Command.java:123) ~[Geyser-Spigot.jar:?]
        at net.onebeastchris.geyser.extension.pickpack.PickPack.onCommandEvent(PickPack.java:117) ~[?:?]
        at Geyser-Spigot.jar/org.lanternpowered.lmbda.Lmbda$5.accept(Unknown Source) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.subscribe.impl.SubscriberImpl.lambda$new$0(SubscriberImpl.java:55) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.subscribe.impl.SubscriberImpl.invoke(SubscriberImpl.java:75) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.bus.impl.BaseBusImpl.fireSilently(BaseBusImpl.java:201) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.bus.impl.OwnedEventBusImpl.fireSilently(OwnedEventBusImpl.java:41) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.bus.impl.BaseBusImpl.fire(BaseBusImpl.java:180) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.bus.impl.OwnedEventBusImpl.fire(OwnedEventBusImpl.java:41) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.command.CommandRegistry.<init>(CommandRegistry.java:163) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.command.CommandRegistry.<init>(CommandRegistry.java:106) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.platform.spigot.command.SpigotCommandRegistry.<init>(SpigotCommandRegistry.java:45) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.onEnable(GeyserSpigotPlugin.java:211) ~[Geyser-Spigot.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[universe-1.21.1.jar:1.21.1-9bef923]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:203) ~[universe-1.21.1.jar:1.21.1-9bef923]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[universe-1.21.1.jar:1.21.1-9bef923]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[universe-1.21.1.jar:1.21.1-9bef923]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:651) ~[universe-1.21.1.jar:1.21.1-9bef923]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:600) ~[universe-1.21.1.jar:1.21.1-9bef923]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:739) ~[universe-1.21.1.jar:1.21.1-9bef923]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:514) ~[universe-1.21.1.jar:1.21.1-9bef923]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:341) ~[universe-1.21.1.jar:1.21.1-9bef923]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[universe-1.21.1.jar:1.21.1-9bef923]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[universe-1.21.1.jar:1.21.1-9bef923]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by onebeastchris** [comment]
This issue is caused by recent Geyser changes around registry loading, and isn't on PickPack's end - please report it on https://github.com/GeyserMC/Geyser/ instead. Thanks!
